#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build pug files to html files ..."
echo "index.pug ..."
./node_modules/.bin/srcbuild-pug src/index.pug -o dist/index.html
echo "build src/quill.snow.styl -> dist/quill.snow.css ..."
./node_modules/.bin/stylus -p src/quill.snow.styl > dist/quill.snow.css
echo "minifying quill.snow.css ..."
./node_modules/.bin/uglifycss dist/quill.snow.css > dist/quill.snow.min.css

echo "done."
